/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p1021;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;

public class Main {

    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st = new StringTokenizer(br.readLine(), " ");
        int n = Integer.parseInt(st.nextToken());
        int itemCount = Integer.parseInt(st.nextToken());
        List<Integer> list = new ArrayList<>();
        for (int i = 1; i <= n; i++) {
            list.add(i);
        }
        int answer = 0;
        StringTokenizer items = new StringTokenizer(br.readLine(), " ");
        for (int i = 0; i < itemCount; i++) {
            int target = Integer.parseInt(items.nextToken());
            int targetRightIndex = list.indexOf(target);
            int targetLeftIndex = list.size() - targetRightIndex;
            answer += Math.min(targetLeftIndex, targetRightIndex);
            list = rotate(list, targetRightIndex);
            list.remove(0);
        }
        System.out.println(answer);
        br.close();
    }

    private static <T> List<T> rotate(List<T> al, int shift) {
        List<T> left = al.subList(0, shift);
        List<T> right = al.subList(shift, al.size());
        List<T> res = new ArrayList<>(right);
        res.addAll(left);
        return res;
    }
}
