/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p1269;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.Set;
import java.util.StringTokenizer;

public class Main {


    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        String[] first = br.readLine().split(" ");
        int aCount = Integer.parseInt(first[0]);
        int bCount = Integer.parseInt(first[1]);

        StringTokenizer stA = new StringTokenizer(br.readLine(), " ");
        Set<Integer> set = new HashSet<>();
        for (int i = 0; i < aCount; i++) {
            set.add(Integer.parseInt(stA.nextToken()));
        }
        int result = 0;
        StringTokenizer stB = new StringTokenizer(br.readLine(), " ");
        for (int i = 0; i < bCount; i++) {
            int current = Integer.parseInt(stB.nextToken());
            if (set.contains(current)) {
                set.remove(current);
                continue;
            }
            result++;
        }
        System.out.println(result + set.size());
    }
}
