/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p4158;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.Set;
import java.util.StringTokenizer;

public class Main {

    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        while (true) {
            StringTokenizer st = new StringTokenizer(br.readLine(), " ");
            int a = Integer.parseInt(st.nextToken());
            int b = Integer.parseInt(st.nextToken());
            if (a == 0 && b == 0) {
                break;
            }
            Set<Integer> set = new HashSet<>();
            for (int i = 0; i < a; i++) {
                set.add(Integer.parseInt(br.readLine()));
            }
            int result = 0;
            for (int i = 0; i < b; i++) {
                if (set.contains(Integer.parseInt(br.readLine()))) {
                    result++;
                }
            }
            System.out.println(result);
        }
        br.close();
    }
}
