/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p2557;

public class Main {

    public static void main(String[] args) {
        System.out.println(new Main().getGreeting());
    }

    public String getGreeting() {
        return "Hello World!";
    }
}
