/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p1764;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Comparator;
import java.util.HashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.StringTokenizer;

public class Main {


    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        StringTokenizer st = new StringTokenizer(br.readLine(), " ");
        int n = Integer.parseInt(st.nextToken());
        int m = Integer.parseInt(st.nextToken());

        Set<String> set = new HashSet<>();
        for (int i = 0; i < n; i++) {
            String name = br.readLine();
            set.add(name);
        }
//ArrayList 와 LinkedList 속도 비교 해보기
        List<String> result = new LinkedList<>();
        for (int i = 0; i < m; i++) {
            String name = br.readLine();
            if (set.contains(name)) {
                result.add(name);
            }
        }
        System.out.println(result.size());
        result.stream()
                .sorted(Comparator.naturalOrder())
                .forEach(System.out::println);
    }
}
