/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p9933;

import java.util.HashSet;
import java.util.Scanner;
import java.util.Set;

public class Main {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        Set<String> result = new HashSet<>();
        int n = Integer.parseInt(sc.nextLine());

        for (int i = 0; i < n; i++) {
            String line = sc.nextLine();
            String reversed = new StringBuilder(line).reverse().toString();
//            System.out.println(reversed);
            result.add(reversed);
            if (result.contains(line)) {
                System.out.println(line.length() + " " + line.charAt(line.length() / 2));
                return;
            }
            result.add(line);
        }
    }
}
