/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p1417;

import java.util.Collections;
import java.util.PriorityQueue;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        PriorityQueue<Integer> queue = new PriorityQueue<>(Collections.reverseOrder());
        int n = sc.nextInt();
        int dasom = sc.nextInt();
        for (int i = 0; i < n - 1; i++) {
            queue.add(sc.nextInt());
        }
        int answer = 0;
        while (!queue.isEmpty() && dasom <= queue.peek()) {
            int max = queue.remove();
            dasom++;
            answer++;
            queue.add(max - 1);
        }
        System.out.println(answer);
    }
}