/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p7758;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Comparator;
import java.util.HashSet;
import java.util.Set;

public class Main {

    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int n = Integer.parseInt(br.readLine());
        Set<String> set = new HashSet<>();
        for (int i = 0; i < n; i++) {
            String[] a = br.readLine().split(" ");
            String nick = a[0];
            String command = a[1];
            if (command.equals("enter")) {
                set.add(nick);
            } else {
                set.remove(nick);
            }
        }
        set.stream()
                .sorted(Comparator.reverseOrder()).forEach(System.out::println);
        br.close();
    }
}
