/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p1302;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Comparator;
import java.util.HashMap;
import java.util.Map.Entry;

public class Main {


    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int n = Integer.parseInt(br.readLine());
        HashMap<String, Integer> map = new HashMap<>();
        for (int i = 0; i < n; i++) {
            String current = br.readLine();
            map.put(current, map.getOrDefault(current, 0) + 1);
        }
        Comparator<Entry<String, Integer>> comp2 = Entry.comparingByKey();
        Comparator<Entry<String, Integer>> comp1 = Comparator.comparingInt(Entry::getValue);
        Entry<String, Integer> result = map.entrySet().stream().sorted(comp2).max(comp1).get();
        System.out.println(result.getKey());
    }
}
