/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p9375;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.HashMap;
import java.util.Map;

public class Main {


    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int testCased = Integer.parseInt(br.readLine());
        for (int t = 0; t < testCased; t++) {
            int n = Integer.parseInt(br.readLine());
            Map<String, Integer> map = new HashMap<>();
            for (int i = 0; i < n; i++) {
                String itemType = br.readLine().split(" ")[1];
                map.put(itemType, map.getOrDefault(itemType, 0) + 1);
            }

            System.out.println(map.values()
                    .stream()
                    .reduce(1, (total, each) -> total * (each + 1)) - 1);
        }
    }
}
