/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p11478;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.HashSet;
import java.util.Set;

public class Main {


    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        String input = br.readLine();
        Set<String> set = new HashSet<>();
        for (int i = 1; i <= input.length(); i++) {
            for (int j = 0; j <= input.length() - i; j++) {
                String temp = input.substring(j, j + i);
                set.add(temp);
            }
        }
        System.out.println(set.size());
    }
}
