/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p3986;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.Stack;

public class Main {

    public static void main(String[] args) throws Exception {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        int n = Integer.parseInt(br.readLine());
        int result = 0;
        for (int i = 0; i < n; i++) {
            String[] temp = br.readLine().split("");
            Stack<String> stack = new Stack<>();
            for (String s : temp) {
                if (!stack.isEmpty()) {
                    String item = stack.peek();
                    if (s.equals(item)) {
                        stack.pop();
                        continue;
                    }
                }
                stack.push(s);
            }
            if (stack.size() == 0) {
                result++;
            }
        }
        System.out.println(result);

    }
}
