/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p2605;

import java.util.LinkedList;
import java.util.List;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        Scanner sc=new Scanner(System.in);

        int n= sc.nextInt();
        List<Integer> students=new LinkedList<>();
        for (int i = 1; i <= n; i++) {
            int a=sc.nextInt();
            students.add(a,i);
        }

        for (int i = n-1; i>=0; i--) {
            System.out.print(students.get(i)+ " ");
        }
    }
}
