/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.p17608;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class Main {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);

        int n = sc.nextInt();
        int max = -1;
        int result = 0;
        List<Integer> sticks = new ArrayList<>();
        for (int i = 0; i < n; i++) {
            int temp = sc.nextInt();
            sticks.add(temp);
        }
        for (int i = n - 1; i >= 0; i--) {
            int temp = sticks.get(i);
            if (temp > max) {
                result++;
                max = temp;
            }
        }
        System.out.println(result);
    }
}
